% usage: change the following file_name to the name of the file generated by the placer
a = dlmread('filename.txt');
[d0,d1] = size(a);
axis auto equal
for n=1:1:d0
  if (n==1)
    rectangle('Position',[a(n,1) a(n,2) a(n,3) a(n,4)],'LineWidth',1);
  else
    rectangle('Position',[a(n,1) a(n,2) a(n,3) a(n,4)],'LineWidth', 1, 'FaceColor', 'cyan', 'EdgeColor','blue');
  end
end