version: 2

jobs:
   "Ubuntu": 
     # Ubuntu 18
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: |
          apt-get -q update -y
          apt-get -y install g++
          apt-get -y install cmake
          apt-get -y install swig
          apt-get -y install flex
          apt-get -y install bison
          apt-get -y install tcl-dev tk-dev
          mkdir build
          cd build
          cmake ..
          make
workflows:
   version: 2
   build:
     jobs: 
        - "Ubuntu"