version: 2

jobs:
   "Ubuntu": 
     # Ubuntu 18
     docker:
       - image: ubuntu:18.04
     steps:
       - checkout
       - run: |
          which g++
          g++ --version
          apt-get -q update -y
          apt-get install g++
          apt-get -y install cmake
          mkdir build
          cd build
          cmake ..
          make
workflows:
   version: 2
   build:
     jobs: 
        - "Ubuntu"