version: 2.1

jobs:
  ubuntu22: # Ubuntu 22
    docker:
      - image: ubuntu:22.04
    steps:
      - run:
          name: "Install ACT"
          command: |
            apt update -y
            apt install -y build-essential git
            apt install -y libedit-dev zlib1g-dev m4
            DEBIAN_FRONTEND=noninteractive TZ=Etc/UTC apt install -y tzdata
            git clone https://github.com/asyncvlsi/act.git --depth 1
            cd act
            mkdir install
            export VLSI_TOOLS_SRC=`pwd`
            export ACT_HOME=$VLSI_TOOLS_SRC/install
            echo export VLSI_TOOLS_SRC=`pwd` >> $BASH_ENV
            echo export ACT_HOME=$VLSI_TOOLS_SRC/install >> $BASH_ENV
            ./configure $ACT_HOME
            ./build
            make install
      - run:
          name: "Install Si2 LEF/DEF parser"
          command: |
            git clone https://github.com/asyncvlsi/lefdef.git --depth 1
            apt-get install -y flex bison
            cd lefdef
            make
            make install
      - run:
          name: "Install phyDB"
          command: |
            apt install -y cmake libboost-all-dev
            git clone https://github.com/asyncvlsi/phyDB.git --depth 1
            cd phyDB
            mkdir build
            cd build
            cmake ..
            make install
      - run:
          name: "Install Dali"
          command: |
            git clone --recursive https://github.com/asyncvlsi/Dali.git --depth 1
            cd Dali
            mkdir build
            cd build
            cmake ..
            make install
            export CTEST_OUTPUT_ON_FAILURE=TRUE
            make test
            
workflows:
  build:
    jobs:
      - ubuntu22