//
// Created by yihan on 8/4/2019.
//

#ifndef HPCC_SRC_PLACER_DETAILEDPLACER_DPABACUS_H_
#define HPCC_SRC_PLACER_DETAILEDPLACER_DPABACUS_H_

class DPAbacus {

};

#endif //HPCC_SRC_PLACER_DETAILEDPLACER_DPABACUS_H_
